HospitalManagement/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from HospitalManagement import settings
from hospital.views import UserLogin

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hospital/", include("hospital.urls", namespace="hospital")),
    path("login/", UserLogin.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospital/urls.py
from django.urls import path
from hospital.views import SignUpDoctorView, SignUpAdminView, SignUpPatientView, success_registration, sign_up_page, \
    ListUsersByGroup, PatientSignUpReview, index, DoctorSignUpReview, review_page

app_name = 'hospital'

urlpatterns = [
    path("", index, name='index'),
    path("register/", sign_up_page, name='register'),
    path("register/doctor", SignUpDoctorView.as_view(), name='register_doctor'),
    path("register/admin", SignUpAdminView.as_view(), name='register_admin'),
    path("register/patient", SignUpPatientView.as_view(), name='register_patient'),
    path("register/success/", success_registration, name='success_page'),
    path("all-users/", ListUsersByGroup.as_view(), name='all_users'),
    path("review/", review_page, name='review_page'),
    path("review/patients", PatientSignUpReview.as_view(), name='patients_review'),
    path("review/doctors", DoctorSignUpReview.as_view(), name='doctors_review'),
]

hospital/models.py
from enum import Enum

from django.db import models
from django.contrib.auth.models import User


class AbstractProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    profile_pic = models.ImageField(upload_to='profile_pic/ProfilePictures/', null=True, blank=True,
                                    default="profile_pic/default.jpg")
    phone = models.CharField(max_length=20, null=True)
    admitDate = models.DateField(auto_now=True)

    class Meta:
        abstract = True


class Specialization(Enum):
    CARDIOLOGIST = 'Cardiologist'
    DERMATOLOGIST = 'Dermatologist'
    DENTIST = 'Dentist'
    ANESTHESIOLOGIST = 'Anesthesiologist'

    @classmethod
    def choices(cls):
        return [(key.value, key.name) for key in cls]


class Doctor(AbstractProfile):
    specialization = models.CharField(max_length=100, choices=Specialization.choices())
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Patient(AbstractProfile):
    symptoms = models.CharField(max_length=150)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Administrator(AbstractProfile):
    def __str__(self):
        return self.user.username

# class Appointment(models.Model):
#     doctor = models.OneToOneField(Doctor, on_delete=models.CASCADE)
#     patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
#     date = models.DateField(auto_now=True)
#     patientName = models.CharField(max_length=100)
#     doctorName = models.CharField(max_length=100)
#     description = models.TextField(max_length=500)
#     status = models.BooleanField(default=False)

hospital/forms.py
from django import forms

from . import models
from .models import Doctor, Patient, Administrator


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['address', 'profile_pic', 'phone', 'specialization']


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['address', 'profile_pic', 'phone', "symptoms"]


class AdministratorForm(forms.ModelForm):
    class Meta:
        model = Administrator
        fields = ['address', 'profile_pic', 'phone']

hospital/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import AccessMixin
from django.contrib.auth.models import Group, User
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView

from .forms import DoctorForm, PatientForm, AdministratorForm
from .models import Patient, Doctor


def index(request):
    return render(request, 'index.html')


def success_registration(request):
    return render(request, 'signup/success_registration.html')


def sign_up_page(request):
    return render(request, 'signup/sign_up_as.html')


def review_page(request):
    return render(request, 'signup_review/review_page.html')


class ProfileSignUpReview(AccessMixin, ListView):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if not self.request.user.groups.filter(name="ADMIN").exists():
            return HttpResponseRedirect(reverse_lazy('hospital:index'))
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(status=False)

    def post(self, request, *args, **kwargs):
        action = request.POST.get('action')
        user_id = request.POST.get('user_id')
        if action == 'approve':
            profile = self.model.objects.get(pk=user_id)
            profile.status = True
            profile.save()
        elif action == 'cancel':
            profile = self.model.objects.get(pk=user_id)
            profile.delete()
        return JsonResponse({"success": True})


class PatientSignUpReview(ProfileSignUpReview):
    template_name = 'signup_review/patients_review.html'
    model = Patient
    context_object_name = 'patient_list'


class DoctorSignUpReview(ProfileSignUpReview):
    template_name = 'signup_review/doctors_review.html'
    model = Doctor
    context_object_name = 'doctor_list'


class ProfileSignupView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('hospital:success_page')
    profile_form_key = None
    group_name = None
    second_form_class = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.profile_form_key not in context:
            context[self.profile_form_key] = self.second_form_class()
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        profile_form = self.second_form_class(self.request.POST, self.request.FILES)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = self.object
            profile_form.save()
            group, _ = Group.objects.get_or_create(name=self.group_name)
            group.user_set.add(self.object)
            return response

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form})


class SignUpDoctorView(ProfileSignupView):
    template_name = 'signup/doctor_sign_up.html'
    second_form_class = DoctorForm
    profile_form_key = "doctorForm"
    group_name = "DOCTOR"


class SignUpPatientView(ProfileSignupView):
    template_name = 'signup/patient_sign_up.html'
    second_form_class = PatientForm
    profile_form_key = "patientForm"
    group_name = "PATIENT"


class SignUpAdminView(ProfileSignupView):
    template_name = 'signup/admin_sign_up.html'
    second_form_class = AdministratorForm
    profile_form_key = "adminForm"
    group_name = "ADMIN"


class UserLogin(LoginView):
    template_name = 'login.html'

    def get_success_url(self):
        return reverse_lazy('hospital:index')


class ListUsersByGroup(View):
    def get(self, request):
        admins = User.objects.filter(groups__name='ADMIN')
        doctors = User.objects.filter(groups__name='DOCTOR')
        patients = User.objects.filter(groups__name='PATIENT')
        return render(request, 'display_users.html', {'admins': admins, 'doctors': doctors, 'patients': patients})

hospital/templates/SignUp/admin_sign_up.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card rounded-0">
                    <div class="card-header">
                        <h3 class="mb-0">Admin SignUp Form</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'hospital:register_admin' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Create Account</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hospital</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body class="text-center">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Hospital</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Page 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Page 2</a>
                </li>
            </ul>
        </div>
        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="#"><span
                        class="bi bi-person-fill"></span>{{ user.username }}</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url "logout" %}"><span
                        class="bi bi-box-arrow-in-right"></span>Logout</a>
                </li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url "hospital:register" %}"><span
                        class="bi bi-person-fill"></span>Sign Up</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url "login" %}"><span
                        class="bi bi-box-arrow-in-right"></span>Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>

<script src="{% static 'js/scripts.js' %}"></script>
</body>

<footer class="container-fluid text-center bg-light py-3">
    <p>Footer Text</p>
</footer>
</html>

hospital/templates/display_users.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <h3 class="mb-5">All users </h3>
            <div class="col-md-4 text-center">
                <h1>Admins</h1>
                {% for admin in admins %}
                    <p>{{ admin.username }}</p>
                {% endfor %}
            </div>
            <div class="col-md-4 text-center">
                <h1>Doctors</h1>
                {% for doctor in doctors %}
                    <p>{{ doctor.username }}</p>
                {% endfor %}
            </div>
            <div class="col-md-4 text-center">
                <h1>Patients</h1>
                {% for patient in patients %}
                    <p>{{ patient.username }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card rounded-0">
                    <div class="card-header">
                        <h3 class="mb-0">Login</h3>
                    </div>
                    <div class="card-body">
                        <h1>Index Page</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card rounded-0">
                    <div class="card-header">
                        <h3 class="mb-0">Login</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'login' %}" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/signUp.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card rounded-0">
                    <div class="card-header">
                        <h3 class="mb-0">Sign Up</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'register' %}" method="post">
                            {% csrf_token %}
                            {{ userForm.as_p }}
                            {{ doctorForm.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Create Account</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/signup/admin_sign_up.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card rounded-0">
                    <div class="card-header">
                        <h3 class="mb-0">Admin SignUp Form</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'hospital:register_admin' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {{ adminForm.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Create Account</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/signup/doctor_sign_up.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card rounded-0">
                    <div class="card-header">
                        <h3 class="mb-0">Doctor Form</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'hospital:register_doctor' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {{ doctorForm.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Create Account</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/signup/patient_sign_up.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card rounded-0">
                    <div class="card-header">
                        <h3 class="mb-0">Patient form</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'hospital:register_patient' %}" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {{ patientForm.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Create Account</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/signup/sign_up_as.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <h3 class="mb-5">Sign up as: </h3>
            <div class="col-md-4 text-center">
                <a href="{% url "hospital:register_doctor" %}">Doctor</a>
            </div>
            <div class="col-md-4 text-center">
                <a href="{% url "hospital:register_patient" %}">Patient</a>
            </div>
            <div class="col-md-4 text-center">
                <a href="{% url "hospital:register_admin" %}">Admin</a>
            </div>
        </div>
    </div>
{% endblock %}

hospital/templates/signup/success_registration.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1>Registration Successful</h1>
        </div>
    </div>
{% endblock content %}

hospital/templates/signup_review/base_review.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row content vh-100">
            <div class="col-sm-2 sidenav">
                <h4>User Information</h4>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item active">Name: John Doe</li>
                    <li class="list-group-item">Age: 30</li>
                    <li class="list-group-item">Location: New York, USA</li>
                </ul>
                <br>
            </div>

            {% block users_list %}
            {% endblock users_list %}
        </div>
    </div>
    <script>const csrf_token = '{{ csrf_token }}';</script>
{% endblock %}

hospital/templates/signup_review/doctors_review.html
{% extends "signup_review/base_review.html" %}

{% block users_list %}
            <div class="col-sm-10">
                <h2>Doctors list to review</h2>
                <div class="row mt-5">
                    <div class="col-4">
                        <div class="list-group" id="list-tab" role="tablist">
                            {% for doctor in doctor_list %}
                                <a class="list-group-item list-group-item-action" id="list-{{ doctor.pk }}-list"
                                   data-bs-toggle="list" href="#list-{{ doctor.pk }}" role="tab"
                                   aria-controls="list-{{ doctor.pk }}">{{ doctor }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-8">

                        <div class="tab-content" id="nav-tabContent">
                            {% for doctor in doctor_list %}
                                <div class="tab-pane fade show" id="list-{{ doctor.pk }}" role="tabpanel"
                                     aria-labelledby="list-{{ doctor.pk }}-list">
                                    <p>User - {{ doctor }}</p>
                                    <button class="btn btn-success"
                                            onclick="sendAjaxData({{ doctor.pk }}, 'approve')">Approve
                                    </button>
                                    <button class="btn btn-danger"
                                            onclick="sendAjaxData({{ doctor.pk }}, 'cancel')">Cancel
                                    </button>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
    <script>
        const review_url = "{% url "hospital:doctors_review" %}";
    </script>
{% endblock users_list %}

hospital/templates/signup_review/patient_review.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row content vh-100">
            <div class="col-sm-2 sidenav">
                <h4>User Information</h4>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item active">Name: John Doe</li>
                    <li class="list-group-item">Age: 30</li>
                    <li class="list-group-item">Location: New York, USA</li>
                </ul>
                <br>
            </div>

            <div class="col-sm-10">
                <h2>Patients list to review</h2>
                <div class="row mt-5">
                    <div class="col-4">
                        <div class="list-group" id="list-tab" role="tablist">
                            {% for patient in patient_list %}
                                <a class="list-group-item list-group-item-action" id="list-{{ patient.pk }}-list"
                                   data-bs-toggle="list" href="#list-{{ patient.pk }}" role="tab"
                                   aria-controls="list-{{ patient.pk }}">{{ patient }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-8">

                        <div class="tab-content" id="nav-tabContent">
                            {% for patient in patient_list %}
                                <div class="tab-pane fade show" id="list-{{ patient.pk }}" role="tabpanel"
                                     aria-labelledby="list-{{ patient.pk }}-list">
                                    <p>User - {{ patient }}</p>
                                    <button class="btn btn-success"
                                            onclick="sendAjaxData({{ patient.pk }}, 'approve')">Approve
                                    </button>
                                    <button class="btn btn-danger"
                                            onclick="sendAjaxData({{ patient.pk }}, 'cancel')">Cancel
                                    </button>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const patient_review_url = "{% url "hospital:patient_review" %}";
        const csrf_token = '{{ csrf_token }}';
    </script>
{% endblock content %}

hospital/templates/signup_review/patients_review.html
{% extends "signup_review/base_review.html" %}

{% block users_list %}
            <div class="col-sm-10">
                <h2>Patients list to review</h2>
                <div class="row mt-5">
                    <div class="col-4">
                        <div class="list-group" id="list-tab" role="tablist">
                            {% for patient in patient_list %}
                                <a class="list-group-item list-group-item-action" id="list-{{ patient.pk }}-list"
                                   data-bs-toggle="list" href="#list-{{ patient.pk }}" role="tab"
                                   aria-controls="list-{{ patient.pk }}">{{ patient }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-8">

                        <div class="tab-content" id="nav-tabContent">
                            {% for patient in patient_list %}
                                <div class="tab-pane fade show" id="list-{{ patient.pk }}" role="tabpanel"
                                     aria-labelledby="list-{{ patient.pk }}-list">
                                    <p>User - {{ patient }}</p>
                                    <button class="btn btn-success"
                                            onclick="sendAjaxData({{ patient.pk }}, 'approve')">Approve
                                    </button>
                                    <button class="btn btn-danger"
                                            onclick="sendAjaxData({{ patient.pk }}, 'cancel')">Cancel
                                    </button>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
    <script>
        const review_url = "{% url "hospital:patients_review" %}";
    </script>
{% endblock users_list %}

hospital/templates/signup_review/review_page.html
{% extends "base.html" %}


{% block content %}
    <div class="container">
        <div class="row">
            <h3 class="mb-5">Review: </h3>
            <div class="col-md-4 text-center">
                <a href="{% url "hospital:doctors_review" %}">Doctor</a>
            </div>
            <div class="col-md-4 text-center">
                <a href="{% url "hospital:patients_review" %}">Patient</a>
            </div>
        </div>
    </div>
{% endblock %}